development:
  bucket: bucket-dev
  access_key_id: xxx
  secret_access_key: xxx
test:
  bucket: bucket-test
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: konsertforeninga
  access_key_id: AKIAIFKQQ4U7OZ3LY46A
  secret_access_key: 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