development:
  bucket: kfbucket
  access_key_id: AKIAIS6ASYTRAN7ALPQQ
  secret_access_key: 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
test:
  bucket: bucket-test
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: kfbucket
  access_key_id: AKIAIS6ASYTRAN7ALPQQ
  secret_access_key: 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